import = ["/home/lowkey/.config/alacritty/gruvbox-dark.toml"]

[font]
normal.family = "Liga SFMono Nerd Font"
normal.style = "Medium"
size = 13.0

italic.family = "Liga SFMono Nerd Font"
italic.style = "Regular Italic"

[window]
blur = true
dynamic_padding = true
dimensions.columns = 100
dimensions.lines = 35
decorations = "Full"
#decorations_theme_variant = "Dark"
